const ACCESS_TOKEN_SECRET=process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET=process.env.REFRESH_TOKEN_SECRET;
const HOST_NAME=process.env.HOST_NAME;

module.exports={ACCESS_TOKEN_SECRET,REFRESH_TOKEN_SECRET,HOST_NAME};